# Generated by Django 4.2.6 on 2023-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_app', '0004_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='group_images/'),
        ),
    ]
