# Generated by Django 4.2.6 on 2023-10-12 15:22

from django.db import migrations, models
import letter_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_app', '0005_alter_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/', validators=[letter_app.models.validate_image]),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/', validators=[letter_app.models.validate_video]),
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message_images/', validators=[letter_app.models.validate_image]),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/', validators=[letter_app.models.validate_video]),
        ),
    ]
