# Generated by Django 4.1.9 on 2023-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_publication_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
