# Generated by Django 4.1.9 on 2023-09-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0007_alter_publication_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
