# Generated by Django 4.1.9 on 2023-09-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0011_remove_comment_parent_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='storage_app.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
