# Generated by Django 4.2.5 on 2023-10-07 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_app', '0014_friendshipstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendshipRequest',
            new_name='Friendship',
        ),
        migrations.DeleteModel(
            name='FriendshipStatus',
        ),
    ]
