# Generated by Django 4.2.5 on 2023-10-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cripyto',
            fields=[
                ('real_id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_id', models.CharField(max_length=64)),
            ],
        ),
    ]
